server:
  port: 8092
spring:
  application:
    name: client_order
  datasource:
    url: jdbc:postgresql://localhost:5432/client_order_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info
    ru.digitalchief.client_order: debug
  file:
    path: ../../
    name: digitalchiefLog.log
  logback:
    rolling policy:
      total-size-cap: 50MB